name: serverwrapper
description: Aurora ServerWrapper
version: 0.1.0
repository: https://github.com/AuroraTeam/ServerWrapper

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  crypto: ^3.0.2
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
