name: serverwrapper
description: Aurora ServerWrapper
version: 1.1.0
repository: https://github.com/AuroraTeam/ServerWrapper

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  crypto: ^3.0.2
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.7.1
  lints: ^2.0.0
  build_runner: ^2.4.6
